const equationParameterMap: Record<string, string[]> = {
  "S<sub>r</sub> = w G<sub>s</sub> / e": [
    "S_r = degree of saturation",
    "w = gravimetric water content",
    "G_s = specific gravity of solids",
    "e = void ratio",
  ],
  "w = (m<sub>wet</sub> - m<sub>dry</sub>) / m<sub>dry</sub>": [
    "w = gravimetric water content",
    "m_wet = wet mass of the sample",
    "m_dry = dry mass of the sample",
  ],
  "&gamma; = W / V": [
    "gamma = bulk or moist unit weight",
    "W = total soil weight",
    "V = total sample volume",
  ],
  "&gamma;<sub>d</sub> = &gamma; / (1 + w)": [
    "gamma_d = dry unit weight",
    "gamma = bulk or moist unit weight",
    "w = gravimetric water content",
  ],
  "&rho;<sub>d</sub> = &gamma;<sub>d</sub> / g": [
    "rho_d = dry density",
    "gamma_d = dry unit weight",
    "g = gravitational acceleration",
  ],
  "&rho; = &gamma; / g": [
    "rho = mass density",
    "gamma = unit weight",
    "g = gravitational acceleration",
  ],
  "G<sub>max</sub> = &rho;V<sub>s</sub><sup>2</sup>": [
    "G_max = maximum small-strain shear modulus",
    "rho = mass density",
    "V_s = shear wave velocity",
  ],
  "G<sub>max</sub> = (&gamma; / g)V<sub>s</sub><sup>2</sup>": [
    "G_max = maximum small-strain shear modulus",
    "gamma = unit weight",
    "g = gravitational acceleration",
    "V_s = shear wave velocity",
  ],
  "E<sub>oed</sub> = 1 / m<sub>v</sub>": [
    "E_oed = one-dimensional constrained or oedometer modulus",
    "m_v = coefficient of volume compressibility",
  ],
  "OCR = &sigma;'<sub>p</sub> / &sigma;'<sub>v0</sub>": [
    "OCR = overconsolidation ratio",
    "sigma'_p = preconsolidation stress",
    "sigma'_v0 = current vertical effective stress",
  ],
  "&sigma;'<sub>v0</sub> = &gamma;z - &gamma;<sub>w</sub> max(z - z<sub>GWT</sub>, 0)": [
    "sigma'_v0 = current vertical effective stress at sample depth",
    "gamma = bulk unit weight (BHA)",
    "z = sample depth",
    "gamma_w = unit weight of water",
    "z_GWT = groundwater table depth",
  ],
  "GI = (F - 35)[0.2 + 0.005(LL - 40)] + 0.01(F - 15)(PI - 10)": [
    "GI = group index",
    "F = percent passing No. 200 sieve",
    "LL = liquid limit",
    "PI = plasticity index",
  ],
  "PI = LL - PL": [
    "PI = plasticity index",
    "LL = liquid limit",
    "PL = plastic limit",
  ],
  "PI<sub>A</sub> = 0.73(LL - 20)": [
    "PI_A = A-line plasticity index",
    "LL = liquid limit",
  ],
  "Screening is rule-based using PI, LL, and fines content thresholds.": [
    "PI = plasticity index",
    "LL = liquid limit",
    "fines content = percentage of fine-grained material, typically passing the No. 200 sieve",
  ],
  "N<sub>q</sub> = e<sup>&pi;tan&phi;'</sup> tan<sup>2</sup>(45 + &phi;'/2)": [
    "N_q = surcharge bearing-capacity factor",
    "e = base of the natural logarithm",
    "pi = circular constant",
    "phi' = effective friction angle",
  ],
  "N<sub>c</sub> = (N<sub>q</sub> - 1) / tan&phi;'": [
    "N_c = cohesion bearing-capacity factor",
    "N_q = surcharge bearing-capacity factor",
    "phi' = effective friction angle",
  ],
  "N<sub>&gamma;,Terzaghi</sub> = 1.5(N<sub>q</sub> - 1)tan&phi;'": [
    "N_gamma,Terzaghi = Terzaghi form of the unit-weight bearing-capacity factor",
    "N_q = surcharge bearing-capacity factor",
    "phi' = effective friction angle",
  ],
  "N<sub>&gamma;,Meyerhof/Hansen</sub> = (N<sub>q</sub> - 1)tan(1.4&phi;')": [
    "N_gamma,Meyerhof/Hansen = Meyerhof and Hansen form of the unit-weight bearing-capacity factor",
    "N_q = surcharge bearing-capacity factor",
    "phi' = effective friction angle",
  ],
  "N<sub>&gamma;,Vesic</sub> = 2(N<sub>q</sub> + 1)tan&phi;'": [
    "N_gamma,Vesic = Vesic form of the unit-weight bearing-capacity factor",
    "N_q = surcharge bearing-capacity factor",
    "phi' = effective friction angle",
  ],
  "tan&phi;'<sub>d</sub> = tan&phi;' / &gamma;<sub>M,&phi;</sub>": [
    "tan phi'_d = tangent of the design friction angle",
    "tan phi' = tangent of the characteristic effective friction angle",
    "gamma_M,phi = Eurocode 7 material factor applied to friction angle",
  ],
  "c'<sub>d</sub> = c' / &gamma;<sub>M,c</sub>": [
    "c'_d = design cohesion",
    "c' = characteristic effective cohesion",
    "gamma_M,c = Eurocode 7 material factor applied to cohesion",
  ],
  "q<sub>Rd</sub> = q<sub>ult,d</sub> / &gamma;<sub>R,v</sub>": [
    "q_Rd = design bearing resistance",
    "q_ult,d = design ultimate bearing resistance before resistance factoring",
    "gamma_R,v = resistance factor for vertical ground resistance",
  ],
  "DA1 Combination 1 = A1 + M1 + R1": [
    "A1 = action factor set 1",
    "M1 = material factor set 1",
    "R1 = resistance factor set 1",
  ],
  "DA1 Combination 2 = A2 + M2 + R1": [
    "A2 = action factor set 2",
    "M2 = material factor set 2",
    "R1 = resistance factor set 1",
  ],
  "DA2 = A1 + M1 + R2": [
    "A1 = action factor set 1",
    "M1 = material factor set 1",
    "R2 = resistance factor set 2",
  ],
  "DA3 = (A1 or A2) + M2 + R3": [
    "A1 or A2 = action factor set chosen for the verification case",
    "M2 = material factor set 2",
    "R3 = resistance factor set 3",
  ],
  "q<sub>ult</sub> = c'N<sub>c</sub>s<sub>c</sub> + qN<sub>q</sub>s<sub>q</sub> + 0.5&gamma;BN<sub>&gamma;</sub>s<sub>&gamma;</sub>": [
    "q_ult = ultimate bearing pressure",
    "c' = effective cohesion",
    "N_c, N_q, N_gamma = bearing capacity factors",
    "s_c, s_q, s_gamma = footing shape factors",
    "q = surcharge pressure at foundation level",
    "gamma = effective unit weight of soil",
    "B = footing width",
  ],
  "q<sub>ult</sub> = c'N<sub>c</sub>s<sub>c</sub>d<sub>c</sub> + qN<sub>q</sub>s<sub>q</sub>d<sub>q</sub> + 0.5&gamma;BN<sub>&gamma;</sub>s<sub>&gamma;</sub>d<sub>&gamma;</sub>": [
    "q_ult = ultimate bearing pressure",
    "c' = effective cohesion",
    "N_c, N_q, N_gamma = bearing capacity factors",
    "s_c, s_q, s_gamma = footing shape factors",
    "d_c, d_q, d_gamma = depth factors",
    "q = surcharge pressure at foundation level",
    "gamma = effective unit weight of soil",
    "B = footing width",
  ],
  "q = &gamma; D<sub>f</sub>": [
    "q = surcharge pressure at foundation level",
    "gamma = unit weight of overlying soil",
    "D_f = embedment depth of footing",
  ],
  "q<sub>all</sub> = q<sub>ult</sub> / FS": [
    "q_all = allowable bearing pressure",
    "q_ult = ultimate bearing pressure",
    "FS = factor of safety",
  ],
  "N<sub>&gamma;</sub> = 2(N<sub>q</sub> + 1)tan&phi;'": [
    "N_gamma = bearing capacity factor for the unit-weight term",
    "N_q = surcharge bearing capacity factor",
    "phi' = effective friction angle",
  ],
  "e<sub>x</sub> = M<sub>y</sub> / P": [
    "e_x = eccentricity along the footing width direction",
    "M_y = bending moment about the y-axis",
    "P = applied vertical load",
  ],
  "e<sub>y</sub> = M<sub>x</sub> / P": [
    "e_y = eccentricity along the footing length direction",
    "M_x = bending moment about the x-axis",
    "P = applied vertical load",
  ],
  "B' = B - 2e<sub>x</sub>": [
    "B' = effective footing width",
    "B = actual footing width",
    "e_x = eccentricity along the width direction",
  ],
  "L' = L - 2e<sub>y</sub>": [
    "L' = effective footing length",
    "L = actual footing length",
    "e_y = eccentricity along the length direction",
  ],
  "q<sub>eff</sub> = P / (B'L')": [
    "q_eff = average effective contact pressure",
    "P = applied vertical load",
    "B' = effective footing width",
    "L' = effective footing length",
  ],
  "s = C<sub>1</sub>C<sub>2</sub>q<sub>net</sub>BI<sub>z(avg)</sub> / E<sub>s</sub>": [
    "s = estimated settlement",
    "C1 = depth correction factor",
    "C2 = creep or time correction factor",
    "q_net = net foundation pressure",
    "B = footing width",
    "I_z(avg) = average strain influence factor",
    "E_s = representative soil modulus",
  ],
  "s<sub>sec</sub> = HC<sub>&alpha;</sub>log(t<sub>2</sub>/t<sub>1</sub>) / (1 + e<sub>p</sub>)": [
    "s_sec = secondary compression settlement",
    "H = compressible layer thickness",
    "C_alpha = secondary compression index",
    "t1 = start time, usually end of primary consolidation",
    "t2 = final time of interest",
    "e_p = void ratio at end of primary consolidation",
  ],
  "s<sub>i</sub> = m<sub>v,i</sub>&Delta;&sigma;'<sub>i</sub>H<sub>i</sub>": [
    "s_i = settlement contribution of layer i",
    "m_v,i = coefficient of volume compressibility of layer i",
    "Delta sigma'_i = effective stress increase in layer i",
    "H_i = thickness of layer i",
  ],
  "s<sub>total</sub> = &Sigma;s<sub>i</sub>": [
    "s_total = total settlement",
    "Sigma s_i = sum of settlement contributions from all layers",
  ],
  "&Delta;&sigma;<sub>z,2:1</sub> = qBL / [(B + z)(L + z)]": [
    "Delta sigma_z,2:1 = average vertical stress increase from the 2:1 spread method",
    "q = applied foundation pressure",
    "B = footing width",
    "L = footing length",
    "z = depth below the footing base",
  ],
  "&Delta;&sigma;<sub>z,30&deg;</sub> = qBL / [(B + 2z tan30&deg;)(L + 2z tan30&deg;)]": [
    "Delta sigma_z,30deg = average vertical stress increase from the 30-degree spread method",
    "q = applied foundation pressure",
    "B = footing width",
    "L = footing length",
    "z = depth below the footing base",
    "tan30deg = tangent of 30 degrees, used to define the side spread",
  ],
  "&Delta;&sigma;<sub>z,B</sub> = &int;&int;<sub>A</sub> (3qz<sup>3</sup> / 2&pi;R<sup>5</sup>) dA": [
    "Delta sigma_z,B = Boussinesq vertical stress beneath the footing centreline",
    "q = applied uniform foundation pressure",
    "z = depth below the footing base",
    "A = loaded rectangular footing area",
    "R = distance from an elemental loaded area to the evaluation point",
    "dA = differential loaded area element",
  ],
  "K<sub>a</sub> = tan<sup>2</sup>(45 - &phi;'/2)": [
    "K_a = active earth pressure coefficient",
    "phi' = effective friction angle of backfill",
  ],
  "K<sub>p</sub> = tan<sup>2</sup>(45 + &phi;'/2)": [
    "K_p = passive earth pressure coefficient",
    "phi' = effective friction angle of backfill",
  ],
  "P<sub>a</sub> = 0.5K<sub>a</sub>&gamma;H<sup>2</sup> + K<sub>a</sub>qH": [
    "P_a = total active earth thrust per unit wall length",
    "K_a = active earth pressure coefficient",
    "gamma = backfill unit weight",
    "H = retained height",
    "q = uniform surcharge",
  ],
  "K<sub>a,C</sub> = cos<sup>2</sup>&phi;' / { cos&delta; [1 + (sin(&phi;' + &delta;) sin&phi;' / cos&delta;)<sup>0.5</sup>] }<sup>2</sup>": [
    "K_a,C = Coulomb active earth pressure coefficient",
    "phi' = effective friction angle of backfill",
    "delta = wall friction angle",
  ],
  "K<sub>0,NC</sub> = 1 - sin&phi;'": [
    "K_0,NC = at-rest earth pressure coefficient for normally consolidated soil",
    "phi' = effective friction angle",
  ],
  "K<sub>0,OC</sub> = K<sub>0,NC</sub> OCR<sup>sin&phi;'</sup>": [
    "K_0,OC = at-rest earth pressure coefficient for overconsolidated soil",
    "K_0,NC = at-rest coefficient for normally consolidated soil",
    "OCR = overconsolidation ratio",
    "phi' = effective friction angle",
  ],
  "Q<sub>s</sub> = f<sub>s</sub>(&pi;DL)": [
    "Q_s = shaft resistance",
    "f_s = unit shaft resistance",
    "pi D = pile perimeter for a circular pile",
    "L = embedded pile length",
  ],
  "Q<sub>b</sub> = q<sub>b</sub>(&pi;D<sup>2</sup>/4)": [
    "Q_b = base resistance",
    "q_b = unit base resistance",
    "pi D^2 / 4 = pile base area",
    "D = pile diameter",
  ],
  "Q<sub>all</sub> = (Q<sub>s</sub> + Q<sub>b</sub>) / FS": [
    "Q_all = allowable axial pile capacity",
    "Q_s = shaft resistance",
    "Q_b = base resistance",
    "FS = factor of safety",
  ],
  "f<sub>s</sub> = C&sigma;<sub>ref</sub>": [
    "f_s = unit shaft resistance",
    "C = selected alpha, beta, or lambda coefficient",
    "sigma_ref = reference stress used by the selected method",
  ],
  "Q<sub>s</sub> = f<sub>s</sub>PL": [
    "Q_s = shaft capacity",
    "f_s = unit shaft resistance",
    "P = pile perimeter",
    "L = embedded length",
  ],
  "f<sub>neg</sub> = &beta;<sub>neg</sub>&sigma;'<sub>v</sub>": [
    "f_neg = unit negative skin friction",
    "beta_neg = negative shaft friction coefficient",
    "sigma'_v = average vertical effective stress in the drag zone",
  ],
  "Q<sub>neg</sub> = f<sub>neg</sub>PL<sub>drag</sub>": [
    "Q_neg = downdrag load",
    "f_neg = unit negative skin friction",
    "P = pile perimeter",
    "L_drag = drag length over which downdrag acts",
  ],
  "&eta;<sub>g</sub> = 1 - {arctan(D/s)[(m - 1)n + (n - 1)m]} / (90mn)": [
    "eta_g = pile group efficiency",
    "D = pile diameter",
    "s = pile spacing",
    "m = number of rows",
    "n = number of columns",
  ],
  "s = HC<sub>c</sub>log[( &sigma;'<sub>0</sub> + &Delta;&sigma;' ) / &sigma;'<sub>0</sub>] / (1 + e<sub>0</sub>)": [
    "s = primary consolidation settlement",
    "H = compressible layer thickness",
    "C_c = compression index",
    "sigma'_0 = initial effective stress",
    "Delta sigma' = applied effective stress increase",
    "e_0 = initial void ratio",
  ],
  "T<sub>h</sub> = c<sub>h</sub>t / d<sub>e</sub><sup>2</sup>": [
    "T_h = radial time factor",
    "c_h = horizontal coefficient of consolidation",
    "t = elapsed time",
    "d_e = equivalent influence diameter",
  ],
  "F(n) = ln(d<sub>e</sub>/d<sub>w</sub>) - 0.75": [
    "F(n) = drain geometry factor used in Barron-type solutions",
    "d_e = equivalent influence diameter",
    "d_w = equivalent drain diameter",
  ],
  "U = 1 - exp[-8T<sub>h</sub>/F(n)]": [
    "U = average degree of consolidation",
    "T_h = radial time factor",
    "F(n) = drain geometry factor",
  ],
  "IF = 1 / [1 - a<sub>s</sub>(1 - 1/n)]": [
    "IF = improvement factor",
    "a_s = area replacement ratio",
    "n = stress concentration ratio between stone column and surrounding soil",
  ],
  "CSR = 0.65(a<sub>max</sub>/g)(&sigma;<sub>v0</sub> / &sigma;'<sub>v0</sub>)r<sub>d</sub>": [
    "CSR = cyclic stress ratio",
    "a_max = peak horizontal ground acceleration",
    "g = gravitational acceleration",
    "sigma_v0 = total vertical stress",
    "sigma'_v0 = effective vertical stress",
    "r_d = stress reduction factor",
  ],
  "CRR<sub>7.5</sub> = 1/(34 - N) + N/135 + 50/(10N + 45)<sup>2</sup> - 1/200": [
    "CRR_7.5 = cyclic resistance ratio referenced to magnitude 7.5",
    "N = corrected clean-sand equivalent SPT resistance",
  ],
  "FoS = (CRR<sub>7.5</sub>MSF K<sub>&sigma;</sub>) / CSR": [
    "FoS = factor of safety against liquefaction triggering",
    "CRR_7.5 = cyclic resistance ratio at magnitude 7.5",
    "MSF = magnitude scaling factor",
    "K_sigma = overburden correction factor",
    "CSR = cyclic stress ratio",
  ],
  "&alpha; = 0, &beta; = 1 for FC &le; 5; &alpha; = e<sup>(1.76 - 190 / FC<sup>2</sup>)</sup>, &beta; = 0.99 + FC<sup>1.5</sup> / 1000 for 5 &lt; FC &le; 35; &alpha; = 5, &beta; = 1.2 for FC &gt; 35": [
    "alpha = fines-correction intercept",
    "beta = fines-correction slope",
    "FC = fines content percentage used in this screening procedure",
  ],
  "(N<sub>1</sub>)<sub>60f</sub> = &alpha; + &beta;(N<sub>1</sub>)<sub>60</sub>": [
    "(N1)60f = fines-corrected SPT resistance",
    "alpha = fines-correction intercept",
    "beta = fines-correction slope",
    "(N1)60 = corrected SPT resistance",
  ],
  "CRR<sub>M7.5</sub> = 1 / (34 - N) + N / 135 + 50 / (10N + 45)<sup>2</sup> - 1 / 200": [
    "CRR_M7.5 = cyclic resistance ratio referenced to Mw 7.5",
    "N = fines-corrected SPT resistance, typically taken as (N1)60f",
  ],
  "C<sub>M</sub> = 10<sup>2.24</sup> / M<sub>w</sub><sup>2.56</sup>": [
    "C_M = magnitude correction factor",
    "M_w = earthquake moment magnitude",
  ],
  "r<sub>d</sub> = 1 - 0.00765z for z &le; 9.15 m; r<sub>d</sub> = 1.174 - 0.0267z for 9.15 &lt; z &le; 23 m; r<sub>d</sub> = 0.744 - 0.008z for 23 &lt; z &le; 30 m": [
    "r_d = depth reduction factor",
    "z = sample depth below ground surface",
  ],
  "&tau;<sub>R</sub> = CRR<sub>M7.5</sub>C<sub>M</sub>&sigma;'<sub>v0</sub>": [
    "tau_R = cyclic resistance stress",
    "CRR_M7.5 = cyclic resistance ratio referenced to Mw 7.5",
    "C_M = magnitude correction factor",
    "sigma'_v0 = vertical effective overburden stress",
  ],
  "&tau;<sub>eq</sub> = 0.65&sigma;<sub>v0</sub>PGA r<sub>d</sub>": [
    "tau_eq = equivalent earthquake-induced cyclic shear stress",
    "sigma_v0 = vertical total overburden stress",
    "PGA = peak ground acceleration ratio used in this simplified tool",
    "r_d = depth reduction factor",
  ],
  "FS = &tau;<sub>R</sub> / &tau;<sub>eq</sub>": [
    "FS = factor of safety against liquefaction triggering in this screening tool",
    "tau_R = cyclic resistance stress",
    "tau_eq = equivalent earthquake-induced cyclic shear stress",
  ],
  "&Delta;N<sub>(1,60)</sub> = 0 for FC &le; 5; &Delta;N<sub>(1,60)</sub> = exp(1.63 + 9.7/(FC + 0.01) - (15.7/(FC + 0.01))<sup>2</sup>) for 5 &lt; FC &le; 35; &Delta;N<sub>(1,60)</sub> &le; 5.5": [
    "Delta N_(1,60) = fines-correction increment added to the corrected SPT resistance",
    "FC = fines content percentage",
    "5.5 = upper screening cap commonly applied to the increment",
  ],
  "(N<sub>1</sub>)<sub>60,cs</sub> = (N<sub>1</sub>)<sub>60</sub> + &Delta;N<sub>(1,60)</sub>": [
    "(N1)60,cs = clean-sand equivalent corrected SPT resistance",
    "(N1)60 = corrected SPT resistance before fines adjustment",
    "Delta N_(1,60) = fines-correction increment",
  ],
  "CRR<sub>7.5</sub> = exp[N/14.1 + (N/126)<sup>2</sup> - (N/23.6)<sup>3</sup> + (N/25.4)<sup>4</sup> - 2.8]": [
    "CRR_7.5 = cyclic resistance ratio referenced to Mw 7.5",
    "N = clean-sand equivalent corrected SPT resistance, typically taken as (N1)60,cs",
  ],
  "MSF = 6.9e<sup>-M<sub>w</sub>/4</sup> - 0.058": [
    "MSF = magnitude scaling factor",
    "M_w = earthquake moment magnitude",
  ],
  "FS = (CRR<sub>7.5</sub>MSF) / CSR": [
    "FS = factor of safety against liquefaction triggering in this screening tool",
    "CRR_7.5 = cyclic resistance ratio referenced to Mw 7.5",
    "MSF = magnitude scaling factor",
    "CSR = cyclic stress ratio",
  ],
  "D<sub>r</sub> &asymp; [(N<sub>1</sub>)<sub>60</sub> / 60]<sup>0.5</sup>": [
    "D_r = relative density used in the simplified post-liquefaction strain sequence",
    "(N1)60 = corrected SPT resistance",
    "60 = reference corrected SPT resistance used in this screening correlation",
  ],
  "&gamma;<sub>lim</sub> = max[1.859(1.1 - D<sub>r</sub>)<sup>3</sup>, 0.05]": [
    "gamma_lim = limiting shear strain used as the strain cap in the post-liquefaction sequence",
    "D_r = relative density inferred from corrected SPT resistance",
    "1.859 and 1.1 = constants from the selected simplified limiting-strain expression",
    "0.05 = lower-bound strain in decimal form applied in this screening relation",
  ],
  "F<sub>&alpha;</sub> = 0.032 + 4.7D<sub>r</sub> - 6D<sub>r</sub><sup>2</sup>": [
    "F_alpha = threshold parameter used in the maximum shear strain relation",
    "D_r = relative density inferred from corrected SPT resistance",
  ],
  "&gamma;<sub>max</sub> = 0 for FS &ge; 2; &gamma;<sub>max</sub> = min{&gamma;<sub>lim</sub>, [0.035(2 - FS)(1 - F<sub>&alpha;</sub>)] / [FS - F<sub>&alpha;</sub>]} for F<sub>&alpha;</sub> &lt; FS &lt; 2; &gamma;<sub>max</sub> = &gamma;<sub>lim</sub> for FS &le; F<sub>&alpha;</sub>": [
    "gamma_max = estimated maximum shear strain",
    "FS = liquefaction triggering factor of safety",
    "gamma_lim = limiting shear strain entered by the user",
    "F_alpha = threshold parameter derived from relative density",
  ],
  "&epsilon;<sub>v</sub> = 1.5e<sup>-2.5D<sub>r</sub></sup> min(0.08, &gamma;<sub>max</sub>)": [
    "epsilon_v = volumetric strain used for settlement estimation",
    "D_r = relative density inferred from corrected SPT resistance",
    "gamma_max = estimated maximum shear strain expressed in decimal strain units in the underlying equation",
    "0.08 = upper strain cap applied in this simplified volumetric strain relation",
  ],
  "s = &epsilon;<sub>v</sub>&Delta;H": [
    "s = settlement",
    "epsilon_v = volumetric strain",
    "Delta H = thickness of the liquefiable layer or sublayer",
  ],
  "k<sub>track</sub> = P / &delta;": [
    "k_track = track stiffness",
    "P = applied load",
    "delta = measured vertical deflection",
  ],
  "k<sub>s</sub> = q / &delta;": [
    "k_s = modulus of subgrade reaction",
    "q = applied contact pressure",
    "delta = measured vertical deflection",
  ],
  "s = aN<sup>b</sup>": [
    "s = cumulative ballast settlement",
    "a = empirical coefficient",
    "N = number of load cycles",
    "b = empirical exponent",
  ],
  "u = P / (&delta;s)": [
    "u = distributed track modulus",
    "P = applied load",
    "delta = measured vertical deflection",
    "s = sleeper spacing",
  ],
  "DSI = |s<sub>A</sub> - s<sub>B</sub>| / L": [
    "DSI = differential settlement indicator",
    "s_A = settlement at point A",
    "s_B = settlement at point B",
    "L = evaluation length",
  ],
  "N<sub>60</sub> = N C<sub>E</sub>C<sub>b</sub>C<sub>r</sub>C<sub>s</sub>": [
    "N_60 = standardized SPT blow count",
    "N = measured field blow count",
    "C_E = energy correction factor",
    "C_b = borehole diameter correction factor",
    "C_r = rod length correction factor",
    "C_s = sampler correction factor",
  ],
  "C<sub>E</sub> = ER / 60": [
    "C_E = energy correction factor",
    "ER = measured hammer energy ratio in percent",
  ],
  "C<sub>r</sub> = 0.75 (z &lt; 3 m), 0.80 (3 &le; z &lt; 4 m), 0.85 (4 &le; z &lt; 6 m), 0.95 (6 &le; z &lt; 10 m), 1.00 (10 &le; z &le; 30 m), 0.95 for z &gt; 30 m in this screening implementation": [
    "C_r = rod length correction factor assigned from sample depth",
    "z = sample depth in meters",
    "For z > 30 m, source tables indicate variable values below 1.00; this tool applies 0.95 as a screening default",
  ],
  "C<sub>N</sub> = 9.78(1 / &sigma;'<sub>v0</sub>)<sup>0.5</sup>, 0.40 &le; C<sub>N</sub> &le; 1.70": [
    "C_N = overburden correction factor",
    "sigma'_v0 = effective vertical overburden stress in kPa (kN/m2)",
    "9.78 = coefficient used in the Idriss and Boulanger (2008) screening expression",
    "C_N is bounded between 0.40 and 1.70 in this tool",
  ],
  "(N<sub>1</sub>)<sub>60</sub> = C<sub>N</sub>N<sub>60</sub> &le; 2N<sub>60</sub>": [
    "(N1)_60 = overburden-corrected standardized blow count",
    "C_N = overburden correction factor",
    "N_60 = energy-corrected standardized blow count",
    "2N_60 = practical screening cap applied in this tool",
  ],
  "s<sub>u</sub> = (q<sub>c</sub> - &sigma;<sub>v0</sub>) / N<sub>kt</sub>": [
    "s_u = undrained shear strength",
    "q_c = cone tip resistance",
    "sigma_v0 = total vertical stress",
    "N_kt = cone factor",
  ],
  "&phi;' &asymp; 17.6 + 11log<sub>10</sub>(q<sub>c</sub>/P<sub>a</sub>)": [
    "phi' = approximate effective friction angle",
    "q_c = cone tip resistance",
    "P_a = atmospheric reference pressure",
  ],
  "E<sub>vd</sub> &asymp; 1.5r&sigma; / s": [
    "E_vd = approximate light weight deflectometer modulus",
    "r = plate radius",
    "sigma = applied plate stress",
    "s = measured deflection",
  ],
  "k = &Delta;q / &Delta;s": [
    "k = secant modulus of subgrade reaction",
    "Delta q = pressure increment",
    "Delta s = settlement increment",
  ],
  "E &asymp; (&pi;a/2)(1 - &nu;<sup>2</sup>)k": [
    "E = approximate elastic modulus",
    "pi = circular constant",
    "a = plate radius",
    "nu = Poisson's ratio",
    "k = modulus of subgrade reaction from the test increment",
  ],
  "c<sub>u</sub>(z) = c<sub>u0</sub> + kz": [
    "c_u(z) = undrained shear strength at depth z",
    "c_u0 = surface undrained shear strength",
    "k = strength gradient with depth",
    "z = depth",
  ],
  "c<sub>u</sub> = f<sub>1</sub>N<sub>60</sub>": [
    "c_u = undrained shear strength",
    "f1 = Stroud plasticity-index factor selected from the PI band",
    "N_60 = corrected SPT resistance",
  ],
  "f<sub>1</sub> is obtained by linear interpolation between the Stroud (1974) PI anchor points.": [
    "f1 = Stroud factor used with corrected SPT resistance",
    "PI = plasticity index used to select/interpolate f1",
    "Anchor points = interpreted Stroud chart values used for interpolation",
  ],
  "&phi;' &asymp; 27.1 + 0.3N<sub>60</sub> - 0.00054N<sub>60</sub><sup>2</sup>": [
    "phi' = approximate effective friction angle",
    "N_60 = corrected SPT resistance",
  ],
  "E = (E/c<sub>u</sub>)c<sub>u</sub>": [
    "E = estimated elastic modulus",
    "E/c_u = selected modulus-to-strength ratio",
    "c_u = undrained shear strength",
  ],
  "M<sub>r</sub> &asymp; 10.34CBR": [
    "M_r = resilient modulus",
    "CBR = California Bearing Ratio",
  ],
};

export function getEquationParameters(equation: string): string[] {
  return (
    equationParameterMap[equation] ?? [
      "Parameter definitions for this expression should be interpreted from the tool methodology and selected inputs.",
    ]
  );
}
